// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhX89zL_ztrS9msphsRz_0dAr9zWewhk',
    appId: '1:831140285549:web:1a8621ae0a807444588364',
    messagingSenderId: '831140285549',
    projectId: 'wellnest-f4f60',
    authDomain: 'wellnest-f4f60.firebaseapp.com',
    storageBucket: 'wellnest-f4f60.firebasestorage.app',
    measurementId: 'G-33VBT1BXE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ALXAOpbUyh77B06N0iUZ-bff6TJRd8A',
    appId: '1:831140285549:android:188efac2e84ae554588364',
    messagingSenderId: '831140285549',
    projectId: 'wellnest-f4f60',
    storageBucket: 'wellnest-f4f60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJB8m9yKznYDwq0rj8qG0gmUx1ip1gqY',
    appId: '1:831140285549:ios:efaacf5244e1512d588364',
    messagingSenderId: '831140285549',
    projectId: 'wellnest-f4f60',
    storageBucket: 'wellnest-f4f60.firebasestorage.app',
    iosBundleId: 'com.example.wellnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJB8m9yKznYDwq0rj8qG0gmUx1ip1gqY',
    appId: '1:831140285549:ios:efaacf5244e1512d588364',
    messagingSenderId: '831140285549',
    projectId: 'wellnest-f4f60',
    storageBucket: 'wellnest-f4f60.firebasestorage.app',
    iosBundleId: 'com.example.wellnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkhX89zL_ztrS9msphsRz_0dAr9zWewhk',
    appId: '1:831140285549:web:e76af33bafaa628d588364',
    messagingSenderId: '831140285549',
    projectId: 'wellnest-f4f60',
    authDomain: 'wellnest-f4f60.firebaseapp.com',
    storageBucket: 'wellnest-f4f60.firebasestorage.app',
    measurementId: 'G-DNKB98V0JS',
  );
}
